<h1>Hello and Welcome!</h1>
<hr>

<?php if($this->flashSession->has('err')) : ?>
    <div class="alert alert-danger">
        <?php $this->flashSession->output() ?>
    </div>
<?php endif; ?>

<?php if($this->flashSession->has('succ')) : ?>
    <div class="alert alert-success">
        <?php $this->flashSession->output() ?>
    </div>
<?php endif; ?>

    <div class="row">
        <div class="col-md-5">
            <h1>Login</h1>
            If you already have an account please <u>login</u> to your profile
            <br><br>
            <?php echo $this->tag->form("login/index"); ?>
                <input class="form-control" type="email" name="email" value="" placeholder="Enter your email *" minlength="7" maxlength="70" required>
                <br>
                <input class="form-control" type="password" name="password" placeholder="Enter password *" minlength="5" maxlength="70" required>
                <br><br>
                <button type="submit" class="btn btn-success" name="login">Login</button>
            </form>
        </div>

        <div class="col-md-offset-2 col-md-5 text-right">
            <h1>Register</h1>
            If you don't have an account please <u>register</u> in to your profile
            <br><br>
            <?php echo $this->tag->form("login/register"); ?>
                <input class="form-control" type="email" name="email" placeholder="Enter your email *" minlength="5" maxlength="70" required>
                <br>
                <input class="form-control" type="password" name="password" placeholder="Enter password *" minlength="5" maxlength="70" required>
                <br><br>
                <button type="submit" class="btn btn-info" name="register">Register</button>
            </form>
        </div>
    </div>