<div class="row">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-3">
                <h3><?php echo $email; ?></h3>
                <br>
                <a href="//localhost/myapp/profile">
                    <img class="img-responsive" src="//localhost/myapp/img/placeholder.png" />
                </a>
            </div>
            <div class="col-md-offset-1 col-md-8">
                <h3>All yours and friends posts</h3>
                <hr>
                <?php if(count($page) > 0) : ?>
                <table class="table table-striped">
                    <thead>
                        <th>Posted by</th>
                        <th>Content</th>
                        <th>Created At</th>
                    </thead>
                    <tbody>
                    <?php foreach($page->items as $item) : ?>
                        <tr>
                            <td><?php echo $item->email; ?></td>
                            <td><?php echo $item->content; ?></td>
                            <td><?php echo date('d/m/Y H:i', strtotime($item->created_at)); ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
                <br>
                <a href='//localhost/myapp/profile'>First</a>
                <a href='//localhost/myapp/profile?page=<?= $page->before; ?>'>Previous</a>
                <a href='//localhost/myapp/profile?page=<?= $page->next; ?>'>Next</a>
                <a href='//localhost/myapp/profile?page=<?= $page->last; ?>'>Last</a>
                <br><br>
                <?php echo 'You are in page ', $page->current, ' of ', $page->total_pages; ?>
                <?php else : ?>
                    <h4>There are no posts at all by you or your friends.</h4>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>